set -g prefix C-a

unbind a
bind a send-prefix

unbind C-a
bind C-a select-pane -l

unbind \;
bind \; select-pane -t :.+

set -sg escape-time 10
set -g focus-events on

set -g pane-border-style fg=colour238
set -g pane-active-border-style fg=green
set -g pane-border-indicators arrows
set -g pane-border-status top
set -g pane-border-format " #P: #{pane_current_command} "
